import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
const output='docs/geography-screenshots';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'});
const base=process.env.PREVIEW_URL||'http://127.0.0.1:5173';const results=[];const errors=[];
const check=async(name,run)=>{try{await run();results.push({name,status:'PASS'});}catch(error){results.push({name,status:'FAIL',detail:error.message});}};
const newPage=async(width=390,height=844)=>{const page=await browser.newPage({viewport:{width,height}});page.on('pageerror',e=>errors.push(e.message));return page;};
async function ready(page){await page.goto(base+'/#/ride');await page.locator('.village-pin').first().waitFor();await page.evaluate(()=>document.fonts.ready);}
async function noOverflow(page){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');}
async function labelsDoNotOverlap(page){assert.ok(await page.locator('.map-card').evaluate(card=>{const box=card.getBoundingClientRect();const labels=[...card.querySelectorAll('.pin-name')].filter(el=>getComputedStyle(el).display!=='none').map(el=>el.getBoundingClientRect());const controls=[...card.querySelectorAll('.map-tools,.map-status,.map-heading span,.map-attribution,.pin-dot')].map(el=>el.getBoundingClientRect());const intersects=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;return labels.every((r,i)=>r.left>=box.left&&r.right<=box.right&&r.top>=box.top&&r.bottom<=box.bottom&&!labels.slice(i+1).some(other=>intersects(r,other))&&!controls.some(other=>intersects(r,other)));}),'clipped or overlapping map label');}
await check('390px: real map, local requests, synchronized selection and no invented service',async()=>{
  const page=await newPage();const requests=[];page.on('request',r=>requests.push(r.url()));await ready(page);assert.equal(await page.locator('.village-pin').count(),5);
  await page.locator('.village-pin[data-village-id=qingtan]').click();assert.equal(await page.locator('.village-summary').getAttribute('data-selected-village-id'),'qingtan');assert.equal(await page.locator('.village-options [data-village-id=qingtan]').getAttribute('aria-pressed'),'true');
  await page.locator('.village-options [data-village-id=longgong]').click();await page.locator('.village-options [data-village-id=ruoao]').click();assert.equal(await page.locator('.village-summary').getAttribute('data-selected-village-id'),'ruoao');assert.equal(await page.locator('.village-pin[data-village-id=ruoao]').getAttribute('aria-pressed'),'true');
  await page.locator('.village-options [data-village-id=xujiashan]').click();await page.evaluate(()=>scrollTo(0,0));await noOverflow(page);assert.ok(requests.every(url=>url.startsWith(base)||url.startsWith('data:')||url.startsWith('blob:')),'external tile/request');assert.doesNotMatch(await page.locator('body').innerText(),/白溪舆记|S-384|5路|3分钟|158/);await page.screenshot({path:output+'/phone-standard.png',fullPage:true});await page.close();
});
for(const [width,height] of [[320,568],[360,740],[768,1024],[1440,1024]]) await check(`${width}px responsive layout`,async()=>{const page=await newPage(width,height);await ready(page);await noOverflow(page);await labelsDoNotOverlap(page);assert.ok(await page.locator('.map-attribution').isVisible());await page.screenshot({path:`${output}/${width}.png`,fullPage:true});await page.close();});
await check('390px large typography and label collision layout',async()=>{const page=await newPage();await ready(page);await page.getByRole('button',{name:'大',exact:true}).click();await noOverflow(page);await labelsDoNotOverlap(page);await page.screenshot({path:output+'/390-large.png',fullPage:true});await page.close();});
await check('large text and 200% text reflow',async()=>{const page=await newPage(320,568);await ready(page);await page.getByRole('button',{name:'大',exact:true}).click();await noOverflow(page);assert.equal(await page.locator('.desktop-navigation').isVisible(),false);await page.screenshot({path:output+'/phone-large.png',fullPage:true});await page.evaluate(()=>document.querySelector('.geography-app').style.setProperty('--body-size','40px'));await noOverflow(page);await page.screenshot({path:output+'/text-200.png',fullPage:true});await page.close();});
await check('right drawer keyboard navigation, Escape and focus restoration',async()=>{const page=await newPage();await ready(page);await page.getByRole('button',{name:'打开右侧导航'}).click();assert.ok(await page.getByRole('dialog').isVisible());await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.getByRole('button',{name:'打开右侧导航'}).evaluate(el=>el===document.activeElement),true);await page.getByRole('button',{name:'打开右侧导航'}).click();await page.getByRole('dialog').getByRole('button',{name:'帮助',exact:true}).click();await page.getByLabel('老年人模式').check();await page.getByRole('button',{name:'返回选择古村'}).click();assert.equal(await page.locator('.map-card').count(),0);assert.equal(await page.locator('.village-options button').count(),5);await noOverflow(page);await page.screenshot({path:output+'/senior.png',fullPage:true});await page.reload();assert.equal(await page.locator('.senior-mode').count(),1);await page.close();});
await check('previous release preferences migrate; reduced motion stays enabled',async()=>{const page=await newPage();await page.addInitScript(()=>localStorage.setItem('baixi.mobile.v2',JSON.stringify({size:'L',quiet:true,senior:false})));await ready(page);assert.equal(await page.locator('.large-type').count(),1);assert.equal(await page.locator('html').getAttribute('data-motion'),'reduced');await page.close();});
for(const mode of ['http','invalid','webgl','storage'])await check(`${mode} failure keeps village information accessible`,async()=>{const page=await newPage();if(mode==='http')await page.route('**/geography/roads.geojson',r=>r.fulfill({status:503,body:'unavailable'}));if(mode==='invalid')await page.route('**/geography/water.geojson',r=>r.fulfill({status:200,contentType:'application/json',body:'{"type":"FeatureCollection","features":[]}'}));if(mode==='webgl')await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(String(type).startsWith('webgl'))return null;return original.call(this,type,...args);};});if(mode==='storage')await page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('disabled')};Storage.prototype.setItem=()=>{throw new Error('disabled')};});await page.goto(base);if(mode==='storage')assert.ok(await page.getByText('设置仅在本次使用中生效，浏览器暂时无法保存。').isVisible());else await page.locator('.map-message').waitFor();await page.locator('.village-options [data-village-id=longgong]').click();assert.equal(await page.locator('.village-summary').getAttribute('data-selected-village-id'),'longgong');await noOverflow(page);if(mode==='http')await page.screenshot({path:output+'/map-fallback.png',fullPage:true});await page.close();});
await check('desktop groove follows selection while icons keep fixed slots',async()=>{const page=await newPage(1440,1024);await ready(page);const positions=await page.locator('.groove-item').evaluateAll(items=>items.map(el=>el.getBoundingClientRect().y));const before=await page.locator('.groove-outline').getAttribute('d');await page.getByRole('button',{name:'返程',exact:true}).click();await page.waitForTimeout(600);assert.notEqual(await page.locator('.groove-outline').getAttribute('d'),before);assert.deepEqual(await page.locator('.groove-item').evaluateAll(items=>items.map(el=>el.getBoundingClientRect().y)),positions);assert.match(await page.locator('main').innerText(),/没有经过运营方确认/);await page.close();});
results.push({name:'uncaught browser errors',status:errors.length?'FAIL':'PASS',detail:errors});
await browser.close();await writeFile('docs/geography-browser-results.json',JSON.stringify({date:'2026-10-08',base,results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
